const CONTINENT_MAP = {
    // Africa
    DZA: "Africa",
    AGO: "Africa",
    BEN: "Africa",
    BWA: "Africa",
    BFA: "Africa",
    BDI: "Africa",
    CPV: "Africa",
    CMR: "Africa",
    CAF: "Africa",
    TCD: "Africa",
    COM: "Africa",
    COG: "Africa",
    COD: "Africa",
    CIV: "Africa",
    DJI: "Africa",
    EGY: "Africa",
    GNQ: "Africa",
    ERI: "Africa",
    SWZ: "Africa",
    ETH: "Africa",
    GAB: "Africa",
    GMB: "Africa",
    GHA: "Africa",
    GIN: "Africa",
    GNB: "Africa",
    KEN: "Africa",
    LSO: "Africa",
    LBR: "Africa",
    LBY: "Africa",
    MDG: "Africa",
    MWI: "Africa",
    MLI: "Africa",
    MRT: "Africa",
    MUS: "Africa",
    MAR: "Africa",
    MOZ: "Africa",
    NAM: "Africa",
    NER: "Africa",
    NGA: "Africa",
    RWA: "Africa",
    STP: "Africa",
    SEN: "Africa",
    SYC: "Africa",
    SLE: "Africa",
    SOM: "Africa",
    ZAF: "Africa",
    SSD: "Africa",
    SDN: "Africa",
    TZA: "Africa",
    TGO: "Africa",
    TUN: "Africa",
    UGA: "Africa",
    ZMB: "Africa",
    ZWE: "Africa",

    // Asia
    AFG: "Asia",
    ARM: "Asia",
    AZE: "Asia",
    BHR: "Asia",
    BGD: "Asia",
    BTN: "Asia",
    BRN: "Asia",
    KHM: "Asia",
    CHN: "Asia",
    CYP: "Asia",
    GEO: "Asia",
    IND: "Asia",
    IDN: "Asia",
    IRN: "Asia",
    IRQ: "Asia",
    ISR: "Asia",
    JPN: "Asia",
    JOR: "Asia",
    KAZ: "Asia",
    KWT: "Asia",
    KGZ: "Asia",
    LAO: "Asia",
    LBN: "Asia",
    MYS: "Asia",
    MDV: "Asia",
    MNG: "Asia",
    MMR: "Asia",
    NPL: "Asia",
    PRK: "Asia",
    OMN: "Asia",
    PAK: "Asia",
    PHL: "Asia",
    QAT: "Asia",
    SAU: "Asia",
    SGP: "Asia",
    KOR: "Asia",
    LKA: "Asia",
    SYR: "Asia",
    TWN: "Asia",
    TJK: "Asia",
    THA: "Asia",
    TLS: "Asia",
    TUR: "Asia",
    TKM: "Asia",
    ARE: "Asia",
    UZB: "Asia",
    VNM: "Asia",
    YEM: "Asia",

    // Europe
    ALB: "Europe",
    AND: "Europe",
    AUT: "Europe",
    BLR: "Europe",
    BEL: "Europe",
    BIH: "Europe",
    BGR: "Europe",
    HRV: "Europe",
    CZE: "Europe",
    DNK: "Europe",
    EST: "Europe",
    FIN: "Europe",
    FRA: "Europe",
    DEU: "Europe",
    GRC: "Europe",
    HUN: "Europe",
    ISL: "Europe",
    IRL: "Europe",
    ITA: "Europe",
    LVA: "Europe",
    LIE: "Europe",
    LTU: "Europe",
    LUX: "Europe",
    MLT: "Europe",
    MDA: "Europe",
    MCO: "Europe",
    MNE: "Europe",
    NLD: "Europe",
    MKD: "Europe",
    NOR: "Europe",
    POL: "Europe",
    PRT: "Europe",
    ROU: "Europe",
    RUS: "Europe",
    SMR: "Europe",
    SRB: "Europe",
    SVK: "Europe",
    SVN: "Europe",
    ESP: "Europe",
    SWE: "Europe",
    CHE: "Europe",
    UKR: "Europe",
    GBR: "Europe",
    VAT: "Europe",

    // North America
    CAN: "North America",
    USA: "North America",
    MEX: "North America",
    GTM: "North America",
    BLZ: "North America",
    HND: "North America",
    SLV: "North America",
    NIC: "North America",
    CRI: "North America",
    PAN: "North America",
    CUB: "North America",
    HTI: "North America",
    DOM: "North America",
    JAM: "North America",
    BHS: "North America",
    BRB: "North America",
    TTO: "North America",
    GRD: "North America",
    DMA: "North America",
    LCA: "North America",
    VCT: "North America",
    ATG: "North America",
    KNA: "North America",

    // South America
    ARG: "South America",
    BOL: "South America",
    BRA: "South America",
    CHL: "South America",
    COL: "South America",
    ECU: "South America",
    GUY: "South America",
    PRY: "South America",
    PER: "South America",
    SUR: "South America",
    URY: "South America",
    VEN: "South America",

    // Oceania
    AUS: "Oceania",
    FJI: "Oceania",
    KIR: "Oceania",
    MHL: "Oceania",
    FSM: "Oceania",
    NRU: "Oceania",
    NZL: "Oceania",
    PLW: "Oceania",
    PNG: "Oceania",
    WSM: "Oceania",
    SLB: "Oceania",
    TON: "Oceania",
    TUV: "Oceania",
    VUT: "Oceania"
};

export async function loadContinentMap() {
    return CONTINENT_MAP;
}